
# This file is automatically generated, you probably don't want to edit this

coxOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "coxOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            elapsed = NULL,
            event = NULL,
            eventLevel = NULL,
            factors = NULL,
            covs = NULL,
            interactions = NULL,
            strata = NULL,
            timeUnit = "none",
            uniMulti = FALSE,
            trend = FALSE,
            coefDetails = FALSE,
            globalTests = TRUE,
            ph = FALSE,
            forest = FALSE,
            phPlot = FALSE,
            adjCurves = FALSE,
            adjKM = TRUE,
            colours = "jmv",
            showExplanations = FALSE, ...) {

            super$initialize(
                package="prognosis",
                name="cox",
                requiresData=TRUE,
                ...)

            private$..elapsed <- jmvcore::OptionVariable$new(
                "elapsed",
                elapsed,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..event <- jmvcore::OptionVariable$new(
                "event",
                event,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..eventLevel <- jmvcore::OptionLevel$new(
                "eventLevel",
                eventLevel,
                variable="(event)")
            private$..factors <- jmvcore::OptionVariables$new(
                "factors",
                factors,
                default=NULL,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                default=NULL,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..interactions <- jmvcore::OptionTerms$new(
                "interactions",
                interactions,
                default=NULL)
            private$..strata <- jmvcore::OptionVariables$new(
                "strata",
                strata,
                default=NULL,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..timeUnit <- jmvcore::OptionList$new(
                "timeUnit",
                timeUnit,
                options=list(
                    "none",
                    "days",
                    "weeks",
                    "months",
                    "years"),
                default="none")
            private$..uniMulti <- jmvcore::OptionBool$new(
                "uniMulti",
                uniMulti,
                default=FALSE)
            private$..trend <- jmvcore::OptionBool$new(
                "trend",
                trend,
                default=FALSE)
            private$..coefDetails <- jmvcore::OptionBool$new(
                "coefDetails",
                coefDetails,
                default=FALSE)
            private$..globalTests <- jmvcore::OptionBool$new(
                "globalTests",
                globalTests,
                default=TRUE)
            private$..ph <- jmvcore::OptionBool$new(
                "ph",
                ph,
                default=FALSE)
            private$..forest <- jmvcore::OptionBool$new(
                "forest",
                forest,
                default=FALSE)
            private$..phPlot <- jmvcore::OptionBool$new(
                "phPlot",
                phPlot,
                default=FALSE)
            private$..adjCurves <- jmvcore::OptionBool$new(
                "adjCurves",
                adjCurves,
                default=FALSE)
            private$..adjKM <- jmvcore::OptionBool$new(
                "adjKM",
                adjKM,
                default=TRUE)
            private$..colours <- jmvcore::OptionList$new(
                "colours",
                colours,
                options=list(
                    "jmv",
                    "set1",
                    "okabe"),
                default="jmv")
            private$..showExplanations <- jmvcore::OptionBool$new(
                "showExplanations",
                showExplanations,
                default=FALSE)

            self$.addOption(private$..elapsed)
            self$.addOption(private$..event)
            self$.addOption(private$..eventLevel)
            self$.addOption(private$..factors)
            self$.addOption(private$..covs)
            self$.addOption(private$..interactions)
            self$.addOption(private$..strata)
            self$.addOption(private$..timeUnit)
            self$.addOption(private$..uniMulti)
            self$.addOption(private$..trend)
            self$.addOption(private$..coefDetails)
            self$.addOption(private$..globalTests)
            self$.addOption(private$..ph)
            self$.addOption(private$..forest)
            self$.addOption(private$..phPlot)
            self$.addOption(private$..adjCurves)
            self$.addOption(private$..adjKM)
            self$.addOption(private$..colours)
            self$.addOption(private$..showExplanations)
        }),
    active = list(
        elapsed = function() private$..elapsed$value,
        event = function() private$..event$value,
        eventLevel = function() private$..eventLevel$value,
        factors = function() private$..factors$value,
        covs = function() private$..covs$value,
        interactions = function() private$..interactions$value,
        strata = function() private$..strata$value,
        timeUnit = function() private$..timeUnit$value,
        uniMulti = function() private$..uniMulti$value,
        trend = function() private$..trend$value,
        coefDetails = function() private$..coefDetails$value,
        globalTests = function() private$..globalTests$value,
        ph = function() private$..ph$value,
        forest = function() private$..forest$value,
        phPlot = function() private$..phPlot$value,
        adjCurves = function() private$..adjCurves$value,
        adjKM = function() private$..adjKM$value,
        colours = function() private$..colours$value,
        showExplanations = function() private$..showExplanations$value),
    private = list(
        ..elapsed = NA,
        ..event = NA,
        ..eventLevel = NA,
        ..factors = NA,
        ..covs = NA,
        ..interactions = NA,
        ..strata = NA,
        ..timeUnit = NA,
        ..uniMulti = NA,
        ..trend = NA,
        ..coefDetails = NA,
        ..globalTests = NA,
        ..ph = NA,
        ..forest = NA,
        ..phPlot = NA,
        ..adjCurves = NA,
        ..adjKM = NA,
        ..colours = NA,
        ..showExplanations = NA)
)

coxResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "coxResults",
    inherit = jmvcore::Group,
    active = list(
        modelTable = function() private$.items[["modelTable"]],
        globalTable = function() private$.items[["globalTable"]],
        coefTable = function() private$.items[["coefTable"]],
        intTable = function() private$.items[["intTable"]],
        subTable = function() private$.items[["subTable"]],
        phTable = function() private$.items[["phTable"]],
        forestPlot = function() private$.items[["forestPlot"]],
        phPlot = function() private$.items[["phPlot"]],
        adjPlots = function() private$.items[["adjPlots"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Cox Regression")
            self$add(jmvcore::Table$new(
                options=options,
                name="modelTable",
                title="Model summary",
                rows=1,
                clearWith=list(
                    "elapsed",
                    "event",
                    "eventLevel",
                    "factors",
                    "covs",
                    "interactions",
                    "strata"),
                columns=list(
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="events", 
                        `title`="Events", 
                        `type`="integer"),
                    list(
                        `name`="cindex", 
                        `title`="C-index", 
                        `type`="number"),
                    list(
                        `name`="clower", 
                        `title`="Lower", 
                        `superTitle`="95% CI", 
                        `type`="number"),
                    list(
                        `name`="cupper", 
                        `title`="Upper", 
                        `superTitle`="95% CI", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="globalTable",
                title="Global tests",
                visible="(globalTests)",
                clearWith=list(
                    "elapsed",
                    "event",
                    "eventLevel",
                    "factors",
                    "covs",
                    "interactions",
                    "strata"),
                columns=list(
                    list(
                        `name`="test", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="chisq", 
                        `title`="\u03C7\u00B2", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="coefTable",
                title="Hazard ratios",
                clearWith=list(
                    "elapsed",
                    "event",
                    "eventLevel",
                    "factors",
                    "covs",
                    "interactions",
                    "strata",
                    "uniMulti",
                    "trend"),
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="level", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="hr_u", 
                        `title`="HR", 
                        `superTitle`="Univariable", 
                        `type`="number", 
                        `visible`="(uniMulti)"),
                    list(
                        `name`="lower_u", 
                        `title`="Lower", 
                        `superTitle`="Univariable", 
                        `type`="number", 
                        `visible`="(uniMulti)"),
                    list(
                        `name`="upper_u", 
                        `title`="Upper", 
                        `superTitle`="Univariable", 
                        `type`="number", 
                        `visible`="(uniMulti)"),
                    list(
                        `name`="p_u", 
                        `title`="p", 
                        `superTitle`="Univariable", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(uniMulti)"),
                    list(
                        `name`="ptrend_u", 
                        `title`="p trend", 
                        `superTitle`="Univariable", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(uniMulti && trend)"),
                    list(
                        `name`="hr", 
                        `title`="HR", 
                        `type`="number"),
                    list(
                        `name`="lower", 
                        `title`="Lower", 
                        `superTitle`="95% CI", 
                        `type`="number"),
                    list(
                        `name`="upper", 
                        `title`="Upper", 
                        `superTitle`="95% CI", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="ptrend", 
                        `title`="p trend", 
                        `type`="number", 
                        `format`="zto,pvalue", 
                        `visible`="(trend)"),
                    list(
                        `name`="beta", 
                        `title`="\u03B2", 
                        `type`="number", 
                        `visible`="(coefDetails)"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number", 
                        `visible`="(coefDetails)"),
                    list(
                        `name`="z", 
                        `title`="z", 
                        `type`="number", 
                        `visible`="(coefDetails)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="intTable",
                title="Interaction tests",
                visible="(length(interactions) > 0)",
                clearWith=list(
                    "elapsed",
                    "event",
                    "eventLevel",
                    "factors",
                    "covs",
                    "interactions",
                    "strata"),
                columns=list(
                    list(
                        `name`="term", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="chisq", 
                        `title`="\u03C7\u00B2", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="subTable",
                title="Hazard ratios within subgroups",
                visible="(length(interactions) > 0)",
                clearWith=list(
                    "elapsed",
                    "event",
                    "eventLevel",
                    "factors",
                    "covs",
                    "interactions",
                    "strata"),
                columns=list(
                    list(
                        `name`="effect", 
                        `title`="Effect of", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="within", 
                        `title`="Within", 
                        `type`="text"),
                    list(
                        `name`="hr", 
                        `title`="HR", 
                        `type`="number"),
                    list(
                        `name`="lower", 
                        `title`="Lower", 
                        `superTitle`="95% CI", 
                        `type`="number"),
                    list(
                        `name`="upper", 
                        `title`="Upper", 
                        `superTitle`="95% CI", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="phTable",
                title="Proportional hazards test",
                visible="(ph)",
                clearWith=list(
                    "elapsed",
                    "event",
                    "eventLevel",
                    "factors",
                    "covs",
                    "interactions",
                    "strata"),
                columns=list(
                    list(
                        `name`="term", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="chisq", 
                        `title`="\u03C7\u00B2", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="forestPlot",
                title="Forest plot",
                width=700,
                height=400,
                renderFun=".forestPlot",
                visible="(forest)",
                clearWith=list(
                    "elapsed",
                    "event",
                    "eventLevel",
                    "factors",
                    "covs",
                    "interactions",
                    "strata",
                    "uniMulti")))
            self$add(jmvcore::Image$new(
                options=options,
                name="phPlot",
                title="Schoenfeld residuals",
                width=700,
                height=450,
                renderFun=".phPlot",
                visible="(phPlot)",
                clearWith=list(
                    "elapsed",
                    "event",
                    "eventLevel",
                    "factors",
                    "covs",
                    "interactions",
                    "strata",
                    "timeUnit")))
            self$add(jmvcore::Array$new(
                options=options,
                name="adjPlots",
                title="Adjusted survival curves",
                visible="(adjCurves)",
                items="(factors)",
                template=jmvcore::Image$new(
                    options=options,
                    title="$key",
                    width=600,
                    height=450,
                    renderFun=".adjPlot",
                    clearWith=list(
                        "elapsed",
                        "event",
                        "eventLevel",
                        "factors",
                        "covs",
                        "interactions",
                        "strata",
                        "adjKM",
                        "colours",
                        "timeUnit"))))}))

coxBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "coxBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "prognosis",
                name = "cox",
                version = c(0,1,0),
                options = options,
                results = coxResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Cox Regression
#'
#' Cox proportional hazards regression with univariable and multivariable 
#' hazard ratios, model tests, proportional-hazards checks and adjusted 
#' survival curves.
#' @param data .
#' @param elapsed .
#' @param event .
#' @param eventLevel .
#' @param factors .
#' @param covs .
#' @param interactions .
#' @param strata .
#' @param timeUnit .
#' @param uniMulti .
#' @param trend .
#' @param coefDetails .
#' @param globalTests .
#' @param ph .
#' @param forest .
#' @param phPlot .
#' @param adjCurves .
#' @param adjKM .
#' @param colours .
#' @param showExplanations .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$modelTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$globalTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$coefTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$intTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$subTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$phTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$forestPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$phPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$adjPlots} \tab \tab \tab \tab \tab an array of images \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$modelTable$asDF}
#'
#' \code{as.data.frame(results$modelTable)}
#'
#' @export
cox <- function(
    data,
    elapsed,
    event,
    eventLevel,
    factors = NULL,
    covs = NULL,
    interactions = NULL,
    strata = NULL,
    timeUnit = "none",
    uniMulti = FALSE,
    trend = FALSE,
    coefDetails = FALSE,
    globalTests = TRUE,
    ph = FALSE,
    forest = FALSE,
    phPlot = FALSE,
    adjCurves = FALSE,
    adjKM = TRUE,
    colours = "jmv",
    showExplanations = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("cox requires jmvcore to be installed (restart may be required)")

    if ( ! missing(elapsed)) elapsed <- jmvcore::resolveQuo(jmvcore::enquo(elapsed))
    if ( ! missing(event)) event <- jmvcore::resolveQuo(jmvcore::enquo(event))
    if ( ! missing(factors)) factors <- jmvcore::resolveQuo(jmvcore::enquo(factors))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if ( ! missing(strata)) strata <- jmvcore::resolveQuo(jmvcore::enquo(strata))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(elapsed), elapsed, NULL),
            `if`( ! missing(event), event, NULL),
            `if`( ! missing(factors), factors, NULL),
            `if`( ! missing(covs), covs, NULL),
            `if`( ! missing(strata), strata, NULL))

    for (v in event) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in factors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in strata) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    if (inherits(interactions, "formula")) interactions <- jmvcore::decomposeFormula(interactions)

    options <- coxOptions$new(
        elapsed = elapsed,
        event = event,
        eventLevel = eventLevel,
        factors = factors,
        covs = covs,
        interactions = interactions,
        strata = strata,
        timeUnit = timeUnit,
        uniMulti = uniMulti,
        trend = trend,
        coefDetails = coefDetails,
        globalTests = globalTests,
        ph = ph,
        forest = forest,
        phPlot = phPlot,
        adjCurves = adjCurves,
        adjKM = adjKM,
        colours = colours,
        showExplanations = showExplanations)

    analysis <- coxClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

