
# This file is automatically generated, you probably don't want to edit this

kmOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "kmOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            elapsed = NULL,
            event = NULL,
            eventLevel = NULL,
            group = NULL,
            timeUnit = "none",
            survTimes = "",
            tests = list(
                "logrank"),
            kmPlot = TRUE,
            cumEvents = FALSE,
            cumHaz = FALSE,
            logLog = FALSE,
            ci = FALSE,
            censor = TRUE,
            riskTable = FALSE,
            medianLine = FALSE,
            markTimes = FALSE,
            pvalPlot = FALSE,
            colours = "jmv",
            xmax = 0,
            xby = 0,
            showExplanations = FALSE, ...) {

            super$initialize(
                package="prognosis",
                name="km",
                requiresData=TRUE,
                ...)

            private$..elapsed <- jmvcore::OptionVariable$new(
                "elapsed",
                elapsed,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..event <- jmvcore::OptionVariable$new(
                "event",
                event,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..eventLevel <- jmvcore::OptionLevel$new(
                "eventLevel",
                eventLevel,
                variable="(event)")
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group,
                default=NULL,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..timeUnit <- jmvcore::OptionList$new(
                "timeUnit",
                timeUnit,
                options=list(
                    "none",
                    "days",
                    "weeks",
                    "months",
                    "years"),
                default="none")
            private$..survTimes <- jmvcore::OptionString$new(
                "survTimes",
                survTimes,
                default="")
            private$..tests <- jmvcore::OptionNMXList$new(
                "tests",
                tests,
                options=list(
                    "logrank",
                    "gehan",
                    "taroneware",
                    "petopeto",
                    "trend"),
                default=list(
                    "logrank"))
            private$..kmPlot <- jmvcore::OptionBool$new(
                "kmPlot",
                kmPlot,
                default=TRUE)
            private$..cumEvents <- jmvcore::OptionBool$new(
                "cumEvents",
                cumEvents,
                default=FALSE)
            private$..cumHaz <- jmvcore::OptionBool$new(
                "cumHaz",
                cumHaz,
                default=FALSE)
            private$..logLog <- jmvcore::OptionBool$new(
                "logLog",
                logLog,
                default=FALSE)
            private$..ci <- jmvcore::OptionBool$new(
                "ci",
                ci,
                default=FALSE)
            private$..censor <- jmvcore::OptionBool$new(
                "censor",
                censor,
                default=TRUE)
            private$..riskTable <- jmvcore::OptionBool$new(
                "riskTable",
                riskTable,
                default=FALSE)
            private$..medianLine <- jmvcore::OptionBool$new(
                "medianLine",
                medianLine,
                default=FALSE)
            private$..markTimes <- jmvcore::OptionBool$new(
                "markTimes",
                markTimes,
                default=FALSE)
            private$..pvalPlot <- jmvcore::OptionBool$new(
                "pvalPlot",
                pvalPlot,
                default=FALSE)
            private$..colours <- jmvcore::OptionList$new(
                "colours",
                colours,
                options=list(
                    "jmv",
                    "set1",
                    "okabe"),
                default="jmv")
            private$..xmax <- jmvcore::OptionNumber$new(
                "xmax",
                xmax,
                min=0,
                default=0)
            private$..xby <- jmvcore::OptionNumber$new(
                "xby",
                xby,
                min=0,
                default=0)
            private$..showExplanations <- jmvcore::OptionBool$new(
                "showExplanations",
                showExplanations,
                default=FALSE)

            self$.addOption(private$..elapsed)
            self$.addOption(private$..event)
            self$.addOption(private$..eventLevel)
            self$.addOption(private$..group)
            self$.addOption(private$..timeUnit)
            self$.addOption(private$..survTimes)
            self$.addOption(private$..tests)
            self$.addOption(private$..kmPlot)
            self$.addOption(private$..cumEvents)
            self$.addOption(private$..cumHaz)
            self$.addOption(private$..logLog)
            self$.addOption(private$..ci)
            self$.addOption(private$..censor)
            self$.addOption(private$..riskTable)
            self$.addOption(private$..medianLine)
            self$.addOption(private$..markTimes)
            self$.addOption(private$..pvalPlot)
            self$.addOption(private$..colours)
            self$.addOption(private$..xmax)
            self$.addOption(private$..xby)
            self$.addOption(private$..showExplanations)
        }),
    active = list(
        elapsed = function() private$..elapsed$value,
        event = function() private$..event$value,
        eventLevel = function() private$..eventLevel$value,
        group = function() private$..group$value,
        timeUnit = function() private$..timeUnit$value,
        survTimes = function() private$..survTimes$value,
        tests = function() private$..tests$value,
        kmPlot = function() private$..kmPlot$value,
        cumEvents = function() private$..cumEvents$value,
        cumHaz = function() private$..cumHaz$value,
        logLog = function() private$..logLog$value,
        ci = function() private$..ci$value,
        censor = function() private$..censor$value,
        riskTable = function() private$..riskTable$value,
        medianLine = function() private$..medianLine$value,
        markTimes = function() private$..markTimes$value,
        pvalPlot = function() private$..pvalPlot$value,
        colours = function() private$..colours$value,
        xmax = function() private$..xmax$value,
        xby = function() private$..xby$value,
        showExplanations = function() private$..showExplanations$value),
    private = list(
        ..elapsed = NA,
        ..event = NA,
        ..eventLevel = NA,
        ..group = NA,
        ..timeUnit = NA,
        ..survTimes = NA,
        ..tests = NA,
        ..kmPlot = NA,
        ..cumEvents = NA,
        ..cumHaz = NA,
        ..logLog = NA,
        ..ci = NA,
        ..censor = NA,
        ..riskTable = NA,
        ..medianLine = NA,
        ..markTimes = NA,
        ..pvalPlot = NA,
        ..colours = NA,
        ..xmax = NA,
        ..xby = NA,
        ..showExplanations = NA)
)

kmResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "kmResults",
    inherit = jmvcore::Group,
    active = list(
        summary = function() private$.items[["summary"]],
        survTable = function() private$.items[["survTable"]],
        tests = function() private$.items[["tests"]],
        kmPlot = function() private$.items[["kmPlot"]],
        cumEventsPlot = function() private$.items[["cumEventsPlot"]],
        cumHazPlot = function() private$.items[["cumHazPlot"]],
        logLogPlot = function() private$.items[["logLogPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Kaplan-Meier")
            self$add(jmvcore::Table$new(
                options=options,
                name="summary",
                title="Survival summary",
                clearWith=list(
                    "elapsed",
                    "event",
                    "eventLevel",
                    "group"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="", 
                        `type`="text", 
                        `visible`="(group)"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="events", 
                        `title`="Events", 
                        `type`="integer"),
                    list(
                        `name`="censored", 
                        `title`="Censored", 
                        `type`="integer"),
                    list(
                        `name`="median", 
                        `title`="Median", 
                        `type`="number"),
                    list(
                        `name`="mlower", 
                        `title`="Lower", 
                        `superTitle`="95% CI", 
                        `type`="number"),
                    list(
                        `name`="mupper", 
                        `title`="Upper", 
                        `superTitle`="95% CI", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="survTable",
                title="Survival at given times",
                clearWith=list(
                    "elapsed",
                    "event",
                    "eventLevel",
                    "group",
                    "survTimes"),
                columns=list(
                    list(
                        `name`="group", 
                        `title`="", 
                        `type`="text", 
                        `combineBelow`=TRUE, 
                        `visible`="(group)"),
                    list(
                        `name`="time", 
                        `title`="Time", 
                        `type`="number"),
                    list(
                        `name`="nrisk", 
                        `title`="At risk", 
                        `type`="integer"),
                    list(
                        `name`="nevent", 
                        `title`="Events", 
                        `type`="integer"),
                    list(
                        `name`="surv", 
                        `title`="Survival", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="lower", 
                        `title`="Lower", 
                        `superTitle`="95% CI", 
                        `type`="number", 
                        `format`="pc"),
                    list(
                        `name`="upper", 
                        `title`="Upper", 
                        `superTitle`="95% CI", 
                        `type`="number", 
                        `format`="pc"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="tests",
                title="Tests comparing groups",
                visible="(length(group) > 0 && length(tests) > 0)",
                clearWith=list(
                    "elapsed",
                    "event",
                    "eventLevel",
                    "group",
                    "tests"),
                columns=list(
                    list(
                        `name`="test", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="chisq", 
                        `title`="\u03C7\u00B2", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="kmPlot",
                title="Survival curve",
                width=600,
                height=450,
                renderFun=".plot",
                visible="(kmPlot)",
                clearWith=list(
                    "elapsed",
                    "event",
                    "eventLevel",
                    "group",
                    "timeUnit",
                    "survTimes",
                    "tests",
                    "ci",
                    "censor",
                    "riskTable",
                    "medianLine",
                    "markTimes",
                    "pvalPlot",
                    "colours",
                    "xmax",
                    "xby")))
            self$add(jmvcore::Image$new(
                options=options,
                name="cumEventsPlot",
                title="Cumulative incidence",
                width=600,
                height=450,
                renderFun=".plot",
                visible="(cumEvents)",
                clearWith=list(
                    "elapsed",
                    "event",
                    "eventLevel",
                    "group",
                    "timeUnit",
                    "survTimes",
                    "tests",
                    "ci",
                    "censor",
                    "riskTable",
                    "medianLine",
                    "markTimes",
                    "pvalPlot",
                    "colours",
                    "xmax",
                    "xby")))
            self$add(jmvcore::Image$new(
                options=options,
                name="cumHazPlot",
                title="Cumulative hazard",
                width=600,
                height=450,
                renderFun=".plot",
                visible="(cumHaz)",
                clearWith=list(
                    "elapsed",
                    "event",
                    "eventLevel",
                    "group",
                    "timeUnit",
                    "survTimes",
                    "tests",
                    "ci",
                    "censor",
                    "riskTable",
                    "medianLine",
                    "markTimes",
                    "pvalPlot",
                    "colours",
                    "xmax",
                    "xby")))
            self$add(jmvcore::Image$new(
                options=options,
                name="logLogPlot",
                title="Log-log plot",
                width=600,
                height=450,
                renderFun=".plot",
                visible="(logLog)",
                clearWith=list(
                    "elapsed",
                    "event",
                    "eventLevel",
                    "group",
                    "timeUnit",
                    "survTimes",
                    "tests",
                    "ci",
                    "censor",
                    "riskTable",
                    "medianLine",
                    "markTimes",
                    "pvalPlot",
                    "colours",
                    "xmax",
                    "xby")))}))

kmBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "kmBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "prognosis",
                name = "km",
                version = c(0,1,0),
                options = options,
                results = kmResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Kaplan-Meier
#'
#' Kaplan-Meier survival estimates, median survival, survival at given times 
#' and rank tests comparing groups.
#' @param data .
#' @param elapsed .
#' @param event .
#' @param eventLevel .
#' @param group .
#' @param timeUnit .
#' @param survTimes .
#' @param tests .
#' @param kmPlot .
#' @param cumEvents .
#' @param cumHaz .
#' @param logLog .
#' @param ci .
#' @param censor .
#' @param riskTable .
#' @param medianLine .
#' @param markTimes .
#' @param pvalPlot .
#' @param colours .
#' @param xmax .
#' @param xby .
#' @param showExplanations .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$summary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$survTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$tests} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$kmPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$cumEventsPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$cumHazPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$logLogPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$summary$asDF}
#'
#' \code{as.data.frame(results$summary)}
#'
#' @export
km <- function(
    data,
    elapsed,
    event,
    eventLevel,
    group = NULL,
    timeUnit = "none",
    survTimes = "",
    tests = list(
                "logrank"),
    kmPlot = TRUE,
    cumEvents = FALSE,
    cumHaz = FALSE,
    logLog = FALSE,
    ci = FALSE,
    censor = TRUE,
    riskTable = FALSE,
    medianLine = FALSE,
    markTimes = FALSE,
    pvalPlot = FALSE,
    colours = "jmv",
    xmax = 0,
    xby = 0,
    showExplanations = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("km requires jmvcore to be installed (restart may be required)")

    if ( ! missing(elapsed)) elapsed <- jmvcore::resolveQuo(jmvcore::enquo(elapsed))
    if ( ! missing(event)) event <- jmvcore::resolveQuo(jmvcore::enquo(event))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(elapsed), elapsed, NULL),
            `if`( ! missing(event), event, NULL),
            `if`( ! missing(group), group, NULL))

    for (v in event) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in group) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- kmOptions$new(
        elapsed = elapsed,
        event = event,
        eventLevel = eventLevel,
        group = group,
        timeUnit = timeUnit,
        survTimes = survTimes,
        tests = tests,
        kmPlot = kmPlot,
        cumEvents = cumEvents,
        cumHaz = cumHaz,
        logLog = logLog,
        ci = ci,
        censor = censor,
        riskTable = riskTable,
        medianLine = medianLine,
        markTimes = markTimes,
        pvalPlot = pvalPlot,
        colours = colours,
        xmax = xmax,
        xby = xby,
        showExplanations = showExplanations)

    analysis <- kmClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

